<?php
$data = array(
  array('a_swim.jpg', 'Swimming', 'The river adjoining the Last Resort is ideal for  swimming (except during the monsoon). The sandbar gently drops into the river  making it safe even for kids. The Last Resort has life jackets and floats which  are a must for any swimming jaunt. Please use them. If you encounter any wild  animal on the other side of the river - stay extremely quiet and hide behind a  bush or tree - and observe. This is a rare sight. '),
  array('a_truck.jpg', 'Trekking', 'Coorg district, with its relatively low density of  population and &quot;Scottish&quot; highlands, is one of the great places to  trek. You can take a medium-tough walk along the riverside from the Last Resort  to the source of the Cauvery - Bagamandala. This trek will cover a range of  bio-diversity which you will not find anywhere else in the country. We need a  day\'s notice to provide a good guide - if you are planning a long trek.&nbsp; There are beautiful walks along the river.  You can take stroll all alone or with a guide.'),
  array('a_bird.jpg', 'Bird Watching', 'There are hundreds of birds that love this organic  farm. The Last Resort is an ornithologist\'s delight. There are river birds like  the snake cormorant down by the paddy fields and many around the house like the  drongo or the minivet. If you sit quietly and observe, there is a virtual  paradise that will unfold itself around you. Very, very de-stressing. A far cry  from rush hour traffic.'),
  array('a_elephant.jpg', 'Elephant Camp', 'Get on a first name basis with an elephant. The  jumbo delight of the Last Resort. Just one mile from the Last Resort is the  Dubare elephant camp. You can trek along the river from the resort. It was set  up by the Forest Department to train elephants. Trained elephants from here not  only help in logging but are also sent for the Dasara celebrations in Mysore, every year. Every  day at 8.30 am the unique Elephant Orientation programme begins and costs about  Rs 200 (separate rates for foreigners). '),
  array('a_rafting.jpg', 'Rafting', 'Whitewater rafting is on during the monsoons when the  river is in spate. <br />
The trip starts at Dubare  (elephant camp) and goes thru a series of rapids close to the Last Resort and  stops just before Kushalnagar. The cost is approximately Rs. 800 per person per  trip. Life jackets are provided. Children below 10 years of age and adults over  55 (especially with a heart condition) are not allowed.'),
  array('a_snooz.jpg', 'Snoozing', 'Sleeping does not sound like a very exciting activity!  But without it - all other activities will lose their spark. At the Last Resort  we can offer you what even some of the best hotels cannot give you - a  peaceful, quiet place to take a short nap or a long, long snooze...', 'CLOSE TO THE RESORT'),
  
  array('b_golf.jpg', 'Coorg is the golfer\'s heaven', '<strong>. Four golf courses</strong> embellish this tiny  district. Three are accessible to the public. Bitangala, near Virajpet has  beautifully laid out greens and a clubhouse. Originally planned by the Sterling  Resorts, it has been taken over and run by the local planters. The planters  have brought in their expert knowledge of cultivation and made it into one of  the best courses in Coorg.<br />
Belur Club near Somvarpet is a  rustic and charming course. The large clubhouse and hospitality makes it a  unique experience to savour.<br />
MDGC. Mercara Downs Golf Course  is a few kilometres from the Madikeri town centre. Although the land is privately owned, one  can get a game by calling the club and reserving a caddy. The hilly  surroundings makes it one of the most picturesque courses in the South of  India.<br />
The fourth at Pollibeta, is owned  by Tata Coffee and will require special permission.'),
  array('b_tibetan.jpg', 'The Tibetan Camp', 'and monastery is only a 5 km away from Kushalnagar. It  is the second largest Tibetans settlement in India and has three majestic gold  coated 40 feet high idols.'),
  array('b_nisargadhama.jpg', 'Nisargadhama', 'is a couple of kilometres from Kushalnagar. It is a  beautiful ecological park, where Cauvery river splits forming a island and a  bamboo forest. It has a hanging bridge, boating, elephant ride, tree top  shelter and deer park.'),
  array('b_nagarahole.jpg', 'Nagarahole', '(Rajiv Gandhi National Park) an excellent opportunity to witness wild animals of  different kinds, from the majestic elephant to the deer, tiger, cheetah, jackal  etc. The forest comprises of valuable wealth like the teak, rosewood, sandal  wood trees etc.'),
  array('b_irpu_falls.jpg', 'Irpu Falls', 'is 15 km away from Nagarahole. A beautiful Shiva Temple  dedicated by Lord Sri Rama is on the banks of the river. Walking besides the  paddy field and watching the gorgeous falls which is about 60 ft is a real  treat to the eyes.', 'AWAY FROM THE RESORT'),

  array('c_madikeri.jpg', 'Kodagu', 'is one of the most beautiful tourist places in South India. <strong>Madikeri  (Mercara)</strong> being its capital, has a population of around 45,000.'),
  array('c_raja.jpg', 'The Kings Throne', 'Overlooking a deep valley is the  delightful garden, the main spot of attraction. <strong>The Raja\'s Seat</strong> is so called because the Raja\'s of Kodagu spent  their evenings at this vintage point watching spectacular sunsets.'),
  array('c_fort.jpg', '', 'In architecture, Madikeri is  unusual. Built on high grounds, the <strong>Madikeri  Fort</strong> looms large over the town. This was rebuilt between 1812-1817. At the  entrance stands the majestic sculpture of horses erected on the entrance wall. It now houses the DC\'s office and civil courts'),
  array('c_omkareshwara.jpg', 'Omkareshwara Temple', 'was built in 1820 by Lingarajendra the then ruling king to ward off the evil  caused by &quot;Brahma Rakshasas&quot;. The Shiva Linga is said to be brought  from the holy place &quot;Kasi&quot;. This temple has an unusual  architectural combination of \'indo-sarsenic\' style.'),
  array('c_abbi_falls.jpg', '', 'A thrilling 8 kilometre drive  through forests and coffee plantations leads to the most popular attraction and  picnic spot - the <strong>Abbi Falls</strong>.  The gushing sound and the beauty of the falls can be experienced from the  hanging bridge.'),
  array('c_talacauvery.jpg', 'Talacauvery', 'the ruling deity goddess of Coorg is the Mother Cauvery.  The birth place of Sacred   River, Cauvery.  Talacauvery is one of the main pilgrim centres of Karnataka. A 48 Km drive from  Madikeri stands Talacauvery at the foot of &quot;Brahmagiri Hills&quot;.'),
);
?>
